apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260526-190219-bcfy8r0dg7d2-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260526-190219-bcfy8r0dg7d2.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260526-190219-bcfy8r0dg7d2-service
            port:
              number: 80
