apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260526-190219-bcfy8r0dg7d2-service
spec:
  selector:
    app: enterprise-system-20260526-190219-bcfy8r0dg7d2
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
